#!/bin/bash

usage() {
	echo "Usage:"
	echo "	./diceRoll <NdM>+, where N > 0 and M > 1"
	echo "	Enter one or more valid dice rolls."
	echo "Example:"
	echo "	./diceRoll 4d6 3d20"
}

if [ "$#" -lt "1" ]; then usage && exit; fi

for i in "${@}"; do
	if [[ "$i" =~ ^[0-9]+d[0-9]+$ ]] && N=$((10#$(echo $i | cut -dd -f1))) && M=$((10#$(echo $i | cut -dd -f2))) && (($N > 0)) && (($M > 1)); then
		res=0
		arr=()
		for j in $(seq 1 $N); do
			x=$(( RANDOM%$M + 1 ))
			((res+=$x))
			arr+=$x' '
		done
		echo $i "-" $res":" ${arr[@]}
	else
		echo "$i -- Not a valid dice roll entry"
	fi
done
