#!/bin/bash

# infinite version of diceRoll!

c=('quit' 'exit' 'done' 'bye' 'q' 'e' 'd' 'b')

usage() {
	echo "Usage:"
	echo "	<NdM>+, where N > 0 and M > 1"
	echo "	Enter one or more valid dice rolls."
	echo "Example:"
	echo "	4d6 3d20"
	echo "rr to reroll"
	echo "Enter any of the following to exit:" ${c[*]}
}

usage
echo

if [ "$#" -gt "0" ]; then
	for i in "${@}"; do
		./diceRoll $i
	done
	echo
fi

while read -r i; do
	if [ "$i" = "" ]; then
		usage
	elif [[ "${c[@]}" =~ "$i" ]]; then
		echo 'Thank you for playing!' && exit
	elif [ "$i" = "rr" ]; then
		[ -n "$last" ] && ./diceRoll $last || echo "Nothing to reroll"
	else
		./diceRoll $i
	fi
	echo
	last=$i
done
