#!/bin/bash

usage() {
	echo "Usage:"
	echo "	./diceRoller <NdM>*"
	echo "	Enter one or more valid dice rolls."
	echo "Example:"
	echo "	./diceRoller 4d6 3d20"
}

if [ "$#" -lt "1" ]; then
	usage
	exit
fi

input=($@)
for i in "${input[@]}"; do
	[[ "$i" =~ ^[0-9]+d[0-9]+$ ]] || { echo "Not a valid dice roll entry" && usage && exit; }
	N=$(echo $i | cut -dd -f1)
	M=$(echo $i | cut -dd -f2)
	res=0
	arr=()
	for j in $(seq 1 $N); do
		x=$(( RANDOM%$M + 1 ))
		((res+=$x))
		arr+=$x' '
	done
	echo $i "-" $res":" ${arr[@]}
done
