#!/bin/bash

# infinite version of diceRoll!

usage() {
	echo "Usage:"
	echo "	<NdM>+, where N > 0 and M > 1"
	echo "	Enter one or more valid dice rolls."
	echo "Example:"
	echo "	4d6 3d20"
}

usage
c=('quit' 'exit' 'done' 'bye' 'q' 'e' 'd' 'b')
while read -r i; do
	if [ "$i" = "" ]; then
		usage
	elif [[ "${c[@]}" =~ "$i" ]]; then
		echo 'Thank you for playing!' && exit
	elif [[ "$i" =~ ^([0-9]+d[0-9]+ *)+$ ]]; then
		./diceRoll $i
	else
		echo "Not a valid dice roll entry" && usage
	fi
	echo
done
